apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      name: blue-deployment-pod
      labels:
        app: v1
    spec:
      containers:
      - name: blue-container
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blue-svc
spec:
  type: NodePort
  selector:
    app: v1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001



apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v2
  template:
    metadata:
      name: green-deployment-pod
      labels:
        app: v2
    spec:
      containers:
      - name: green-container
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: green-svc
spec:
  type: NodePort
  selector:
    app: v2
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002