apiVersion: v1
kind: Pod
metadata:
  name: sbi-pod
  labels:
    app: sbi
spec:
  containers:
  - name: sbi-cont
    image: httpd
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sbi-svc
spec:
  type: NodePort
  selector:
    app: sbi
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
---







apiVersion: v1
kind: Pod
metadata:
  name: sbii-pod
  labels:
    app: sbii
spec:
  containers:
  - name: sbii-cont
    image: httpd
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sbii-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: sbii
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002

